### ISSUE TITLE
make it a notification plugin

### ISSUE THREAD

**Issue by srinivasupadhya** [PagerDuty/gocd-hipchat-plugin#1]
reference [1](http://www.go.cd/documentation/developer/writing_go_plugins/notification/json_message_based_notification_extension.html) & [2](https://github.com/srinivasupadhya/email-notifier).

also do consider adding the plugin to [gocd plugins listing page](http://www.go.cd/community/plugins.html) - [code](https://github.com/gocd/gocd.github.io)

**Comment by ranjib** [comment]
@srinivasupadhya im working on this, but if i understand correctly, notification extension is available on GoCD 15.1 onwards. Do you know when we can expect a stable release of 15.x ?

**Comment by srinivasupadhya** [comment]
Performance Analysis is underway. If all goes well, should be out sometime next week.

**Comment by esigler** [comment]
My apologies, this software is no longer actively being maintained by PagerDuty. We've switched over to Slack, and can no longer easily develop for this plugin. If you want to take over ownership, please email opensource@pagerduty.com.  Closing this issue.
