### ISSUE TITLE
Ability to use on premise Hipchat?

### ISSUE THREAD

**Issue by mikeycmccarthy** [PagerDuty/gocd-hipchat-plugin#10]
Just starting looking at integrating this and I realised this will only work with api.hipchat and non an on-premise Hipchat installation. Would it be possible to add that as an upcoming feature? Thanks!

**Comment by esigler** [comment]
My apologies, this software is no longer actively being maintained by PagerDuty. We've switched over to Slack, and can no longer easily develop for this plugin. If you want to take over ownership, please email opensource@pagerduty.com.  Closing this issue.
